print("Input")
nama = input("Nama                   : ")
nim = input("NIM                    : ")
kls_prl = input("Kelas Paralel          : ")
ttl = input("Tempat/Tanggal Lahir   : ")
alamat = input("Alamat                 : ")
hobby = input("Hobby                  : ")
no_hp = input("No. HP                 : ")
print()
print("Output")
print("Nama                   :", nama)
print("NIM                    :", nim)
print("Kelas Paralel          :", kls_prl)
print("Tempat/Tanggal Lahir   :", ttl)
print("Alamat                 :", alamat)
print("Hobby                  :", hobby)
print("No. HP                 :", no_hp)